window.PLAN_META = { kinds: [
  {k:"stories",  label:"Сторис",     emoji:"📸", color:"#ff8fc7", hint:"Instagram/TG сторис"},
  {k:"reel",     label:"Рилс",       emoji:"🎬", color:"#7cc4ff", hint:"вертикальное видео"},
  {k:"carousel", label:"Карусель",   emoji:"🎠", color:"#ffd166", hint:"Instagram-карусель"},
  {k:"post_ig",  label:"Одиночный пост ИГ", emoji:"🖼️", color:"#c9a4ff", hint:"один слайд/фото в Instagram"},
  {k:"post_tg",  label:"ТГ-пост",    emoji:"📨", color:"#4dabf7", hint:"пост в Telegram-канал"},
  {k:"circle",   label:"Кружок",     emoji:"⭕", color:"#6ee7c4", hint:"видео-кружок"},
  {k:"threads",  label:"Тредс",      emoji:"🧵", color:"#b0b8c4", hint:"пост в Threads"},
  {k:"meme",     label:"Мем",        emoji:"😂", color:"#ff9f9f", hint:"мем/шутка"},
  {k:"draft",    label:"Мастер-текст", emoji:"📝", color:"#ffa64d", hint:"черновик текста, ещё не оформлено"}
]};

window.PLAN_DAYS = [
{d:"26.08", w:"ср", items:[]},
{d:"27.08", w:"чт", items:[]},
{d:"28.08", w:"пт", items:[]},
{d:"29.08", w:"сб", items:[]},
{d:"30.08", w:"вс", items:[]},
{d:"31.08", w:"пн", items:[]},
{d:"01.09", w:"вт", items:[]},
{d:"02.09", w:"ср", items:[]},
{d:"03.09", w:"чт", items:[]},
{d:"04.09", w:"пт", items:[]},
{d:"05.09", w:"сб", items:[]},
{d:"06.09", w:"вс", items:[]},
{d:"07.09", w:"пн", items:[]},
{d:"08.09", w:"вт", items:[]},
{d:"09.09", w:"ср", items:[]},
{d:"10.09", w:"чт", items:[]},
{d:"11.09", w:"пт", items:[]},
{d:"12.09", w:"сб", items:[]},
{d:"13.09", w:"вс", items:[]},
{d:"14.09", w:"пн", items:[]},
{d:"15.09", w:"вт", items:[]},
{d:"16.09", w:"ср", items:[]},
];
